#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: scripts/run_gateway_ota_staging_hil.sh

End-to-end HIL validation for staging OTA bundles generated by package_ota_release.py.

Required environment:
  GATEWAY_BASE_URL    Base HTTP URL of the gateway, e.g. http://192.168.178.171

Manifest source:
  Either provide:
    OTA_MANIFEST_PATH Local manifest JSON path
  or:
    OTA_MANIFEST_URL  Remote manifest JSON URL

Optional environment:
  SCENARIO            success | tampered-signature (default: success)
  SERVE_DIR           Local directory to expose over python3 -m http.server during the run
  HTTP_PORT           Port for SERVE_DIR local server (default: 8877)
  OTA_POLL_TIMEOUT_SEC  OTA result poll timeout (default: 180)
  REBOOT_TIMEOUT_SEC    Post-reboot wait timeout (default: 120)
  GATEWAY_READY_SEC     Gateway readiness wait timeout (default: 30)
  LOG_PATH              Optional sign-off log path

Behavior:
  success:
    - loads a signed staging manifest
    - POSTs it to /api/ota
    - waits for OTA result
    - waits for reboot/recovery
    - verifies current_version == manifest.version

  tampered-signature:
    - loads the same manifest
    - tampers one signed field while preserving signature
    - expects the gateway to reject the request

Notes:
  - The device still downloads the firmware URL from the manifest itself.
  - If SERVE_DIR is used, the manifest's URL must already point to a host/port reachable by the gateway.
EOF
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

test -n "${GATEWAY_BASE_URL:-}" || {
  echo "GATEWAY_BASE_URL is required" >&2
  usage
  exit 2
}

SCENARIO="${SCENARIO:-success}"
HTTP_PORT="${HTTP_PORT:-8877}"
OTA_POLL_TIMEOUT_SEC="${OTA_POLL_TIMEOUT_SEC:-180}"
REBOOT_TIMEOUT_SEC="${REBOOT_TIMEOUT_SEC:-120}"
GATEWAY_READY_SEC="${GATEWAY_READY_SEC:-30}"
LOG_PATH="${LOG_PATH:-gateway-ota-signoff.log}"
SERVE_DIR="${SERVE_DIR:-}"

if [[ "${SCENARIO}" != "success" && "${SCENARIO}" != "tampered-signature" ]]; then
  echo "Unsupported SCENARIO: ${SCENARIO}" >&2
  exit 2
fi

command -v curl >/dev/null 2>&1
command -v python3 >/dev/null 2>&1

SERVER_PID=0
cleanup() {
  if [[ "${SERVER_PID}" -gt 0 ]]; then
    kill "${SERVER_PID}" >/dev/null 2>&1 || true
    wait "${SERVER_PID}" 2>/dev/null || true
  fi
}
trap cleanup EXIT

if [[ -n "${SERVE_DIR}" ]]; then
  test -d "${SERVE_DIR}" || {
    echo "SERVE_DIR does not exist: ${SERVE_DIR}" >&2
    exit 2
  }
  (
    cd "${SERVE_DIR}"
    python3 -m http.server "${HTTP_PORT}" >/tmp/gateway-ota-staging-http.log 2>&1
  ) &
  SERVER_PID=$!
  sleep 2
fi

json_get_expr() {
  local payload="$1"
  local expression="$2"
  python3 - "$payload" "$expression" <<'PY'
import json
import sys

data = json.loads(sys.argv[1])
expr = sys.argv[2]
value = eval(expr, {"__builtins__": {}}, {"data": data})
if isinstance(value, bool):
    print("true" if value else "false")
elif value is None:
    print("")
else:
    print(value)
PY
}

json_load_manifest() {
  if [[ -n "${OTA_MANIFEST_PATH:-}" ]]; then
    test -f "${OTA_MANIFEST_PATH}" || {
      echo "OTA_MANIFEST_PATH does not exist: ${OTA_MANIFEST_PATH}" >&2
      exit 2
    }
    cat "${OTA_MANIFEST_PATH}"
    return
  fi

  if [[ -n "${OTA_MANIFEST_URL:-}" ]]; then
    curl --fail --silent --show-error "${OTA_MANIFEST_URL}"
    return
  fi

  echo "Provide OTA_MANIFEST_PATH or OTA_MANIFEST_URL" >&2
  exit 2
}

wait_for_gateway_ready() {
  local deadline=$(( $(date +%s) + GATEWAY_READY_SEC ))
  while (( $(date +%s) <= deadline )); do
    if curl --fail --silent --show-error "${GATEWAY_BASE_URL}/api/ota" >/dev/null 2>&1; then
      return 0
    fi
    sleep 2
  done
  echo "Gateway did not become ready within ${GATEWAY_READY_SEC}s" >&2
  return 1
}

log_signoff() {
  local line="$1"
  printf '%s\n' "${line}" | tee -a "${LOG_PATH}"
}

manifest_json="$(json_load_manifest)"
manifest_version="$(json_get_expr "${manifest_json}" 'data.get("version", "")')"
manifest_url="$(json_get_expr "${manifest_json}" 'data.get("url", "")')"
manifest_signature="$(json_get_expr "${manifest_json}" 'data.get("signature", "")')"

test -n "${manifest_url}" || {
  echo "Manifest URL is missing" >&2
  exit 1
}

log_signoff "OTA_SIGNOFF start scenario=${SCENARIO} manifest_version=${manifest_version:-<empty>} manifest_url=${manifest_url}"

wait_for_gateway_ready

request_body="$(
  python3 - "${manifest_json}" "${SCENARIO}" <<'PY'
import json
import sys

manifest = json.loads(sys.argv[1])
scenario = sys.argv[2]
if "version" in manifest:
    manifest["target_version"] = manifest.pop("version")
if scenario == "tampered-signature":
    sha = manifest.get("sha256", "")
    if sha:
        manifest["sha256"] = ("0" if sha[0] != "0" else "1") + sha[1:]
    else:
        manifest["url"] = manifest.get("url", "") + "?tampered=1"
print(json.dumps(manifest, separators=(",", ":")))
PY
)"

response_headers="$(mktemp)"
response_body="$(mktemp)"
trap 'rm -f "${response_headers}" "${response_body}"; cleanup' EXIT

status_code="$(
  curl --silent --show-error \
    -D "${response_headers}" \
    -o "${response_body}" \
    -H 'Content-Type: application/json' \
    -X POST \
    --data "${request_body}" \
    -w '%{http_code}' \
    "${GATEWAY_BASE_URL}/api/ota"
)"
response_json="$(cat "${response_body}")"
log_signoff "OTA_SIGNOFF submit status=${status_code} body=${response_json}"

if [[ "${SCENARIO}" == "tampered-signature" ]]; then
  if [[ "${status_code}" != "409" && "${status_code}" != "400" ]]; then
    echo "Expected manifest rejection, got HTTP ${status_code}" >&2
    exit 1
  fi

  error_token="$(json_get_expr "${response_json}" 'data.get("error", "")')"
  if [[ "${error_token}" != "invalid_signature" && "${error_token}" != "signature_required" ]]; then
    echo "Expected invalid signature rejection, got: ${response_json}" >&2
    exit 1
  fi

  log_signoff "OTA_SIGNOFF result scenario=tampered-signature status=pass rejection=${error_token}"
  echo "Gateway OTA staging negative validation PASSED"
  exit 0
fi

if [[ "${status_code}" != "202" ]]; then
  echo "Expected HTTP 202 for OTA acceptance, got ${status_code}" >&2
  exit 1
fi

request_id="$(json_get_expr "${response_json}" 'data.get("request_id", "")')"
test -n "${request_id}" || {
  echo "request_id missing in OTA accepted response" >&2
  exit 1
}

deadline=$(( $(date +%s) + OTA_POLL_TIMEOUT_SEC ))
result_json=""
while (( $(date +%s) <= deadline )); do
  snapshot="$(curl --fail --silent --show-error "${GATEWAY_BASE_URL}/api/ota" || true)"
  if [[ -n "${snapshot}" ]]; then
    log_signoff "OTA_SIGNOFF snapshot ${snapshot}"
  fi

  result_json="$(curl --fail --silent --show-error "${GATEWAY_BASE_URL}/api/ota/result?request_id=${request_id}" || true)"
  if [[ -n "${result_json}" ]]; then
    log_signoff "OTA_SIGNOFF result-poll ${result_json}"
    ready="$(json_get_expr "${result_json}" 'data.get("ready", False)')"
    if [[ "${ready}" == "true" ]]; then
      ok="$(json_get_expr "${result_json}" 'data.get("ok", False)')"
      if [[ "${ok}" != "true" ]]; then
        echo "OTA failed: ${result_json}" >&2
        exit 1
      fi
      break
    fi
  fi

  sleep 2
done

test -n "${result_json}" || {
  echo "OTA result not observed before timeout" >&2
  exit 1
}

reboot_required="$(json_get_expr "${result_json}" 'data.get("reboot_required", False)')"
if [[ "${reboot_required}" != "true" ]]; then
  echo "Expected reboot_required=true for successful OTA" >&2
  exit 1
fi

reboot_deadline=$(( $(date +%s) + REBOOT_TIMEOUT_SEC ))
while (( $(date +%s) <= reboot_deadline )); do
  post_snapshot="$(curl --fail --silent --show-error "${GATEWAY_BASE_URL}/api/ota" || true)"
  if [[ -z "${post_snapshot}" ]]; then
    sleep 2
    continue
  fi

  log_signoff "OTA_SIGNOFF post-reboot ${post_snapshot}"
  current_version="$(json_get_expr "${post_snapshot}" 'data.get("current_version", "")')"
  current_stage="$(json_get_expr "${post_snapshot}" 'data.get("stage", "")')"
  if [[ -n "${manifest_version}" && "${current_version}" == "${manifest_version}" ]]; then
    log_signoff "OTA_SIGNOFF result scenario=success status=pass request_id=${request_id} current_version=${current_version} stage=${current_stage}"
    echo "Gateway OTA staging success validation PASSED"
    exit 0
  fi

  sleep 2
done

echo "Gateway did not return with expected version ${manifest_version} before timeout" >&2
exit 1
