import test from 'node:test';import assert from 'node:assert/strict';import {JSDOM} from 'jsdom';
import {ScenarioEditor,serializeConditions,validateDraft} from '../../components/web_ui/assets/scenario_editor.js';
const devices=[{device_id:'0000000000000001',name:'Дверь',capabilities:['contact'],channels:[]},{device_id:'0000000000000002',name:'PIR',capabilities:['occupancy'],channels:[]},{device_id:'0000000000000003',name:'Реле',capabilities:[],channels:[{channel_id:1},{channel_id:2},{channel_id:3}]}];
const state=(id,cap)=>({kind:'state',device_id:id,capability:cap,op:'eq',value:true});
const tree={kind:'all',children:[{kind:'any',children:[state(devices[0].device_id,'contact'),state(devices[1].device_id,'occupancy')]},{kind:'time_window',start:1380,end:120}]};
const rule={id:1,name:'<img onerror=alert(1)>',enabled:true,triggers:[{device_id:devices[1].device_id,kind:'occupancy.detected'}],conditions:[],actions:[{kind:'set_channel_power',device_id:devices[2].device_id,channel_id:1,on:true},{kind:'delay',delay_ms:60000},{kind:'set_channel_power',device_id:devices[2].device_id,channel_id:1,on:false}]};
test('nested ALL ANY converts to bounded codec indices',()=>{const nodes=serializeConditions(tree);assert.equal(nodes.length,5);assert.deepEqual(nodes[0].children,[1,4]);assert.deepEqual(nodes[1].children,[2,3]);assert.equal(validateDraft({...rule,conditions:nodes},devices),null);});
test('invalid references, empty groups, triggers and depth are rejected',()=>{assert.ok(validateDraft({...rule,triggers:[]},devices));assert.ok(validateDraft({...rule,conditions:[{kind:'all',children:[]}]},devices));assert.ok(validateDraft({...rule,actions:[{...rule.actions[0],channel_id:4}]},devices));let deep=state(devices[0].device_id,'contact');for(let i=0;i<4;i++)deep={kind:'all',children:[deep]};assert.throws(()=>serializeConditions(deep));});
test('name is text; failed save retains draft; double click sends once',async()=>{const dom=new JSDOM('<div id="root"></div>');globalThis.document=dom.window.document;const root=document.getElementById('root');let calls=0,reject;const editor=ScenarioEditor.mount(root,{devices,scenario:rule,onSave:()=>{calls++;return new Promise((_,r)=>{reject=r;});}});assert.equal(root.querySelector('input[name="name"]').value,rule.name);assert.equal(root.querySelectorAll('img').length,0);const first=editor.save();await editor.save();assert.equal(calls,1);reject(new Error('Нет связи'));await first;assert.equal(editor.serialize().name,rule.name);assert.match(root.textContent,/Нет связи/);delete globalThis.document;});
